import { ResumeAnalysis } from "@/types/analysis";

type Props = {
  analysis: ResumeAnalysis;
};

export function ResultsView({ analysis }: Props) {
  const { summary, strengths, weaknesses, suggestions } = analysis;

  return (
    <section className="mt-8 space-y-6">
      <div className="card space-y-2">
        <h2 className="text-base font-semibold text-slate-50">
          Analysis summary
        </h2>
        <p className="text-sm text-slate-300">
          These insights are generated by AI. Use them as guidance, not as
          absolute truth.
        </p>
        <div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-200">
          {summary.name && (
            <span className="badge">
              <span className="mr-1.5 h-1.5 w-1.5 rounded-full bg-emerald-400" />
              {summary.name}
            </span>
          )}
          {summary.primaryRole && (
            <span className="badge">{summary.primaryRole}</span>
          )}
          {summary.yearsOfExperience && (
            <span className="badge">
              {summary.yearsOfExperience} experience
            </span>
          )}
          {summary.headline && (
            <span className="badge">{summary.headline}</span>
          )}
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <div className="card space-y-3">
          <h3 className="text-sm font-semibold text-emerald-300">Strengths</h3>
          {strengths.length === 0 ? (
            <p className="text-sm text-slate-400">
              No clear strengths were extracted, but that does not mean your
              resume is weak. Try uploading a more detailed version.
            </p>
          ) : (
            <ul className="space-y-2 text-sm text-slate-200">
              {strengths.map((item, idx) => (
                <li key={idx} className="flex gap-2">
                  <span className="mt-1 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-emerald-400" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          )}
        </div>

        <div className="card space-y-3">
          <h3 className="text-sm font-semibold text-amber-300">
            Areas to improve
          </h3>
          {weaknesses.length === 0 ? (
            <p className="text-sm text-slate-400">
              No specific gaps were highlighted. You can still use the
              suggestions below to refine your resume.
            </p>
          ) : (
            <ul className="space-y-2 text-sm text-slate-200">
              {weaknesses.map((item, idx) => (
                <li key={idx} className="flex gap-2">
                  <span className="mt-1 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-amber-300" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          )}
        </div>
      </div>

      <div className="card space-y-3">
        <h3 className="text-sm font-semibold text-sky-300">
          Concrete suggestions
        </h3>
        {suggestions.length === 0 ? (
          <p className="text-sm text-slate-400">
            No suggestions available. Try another resume or adjust your file.
          </p>
        ) : (
          <ol className="space-y-2 pl-4 text-sm text-slate-200">
            {suggestions.map((item, idx) => (
              <li key={idx} className="list-decimal">
                {item}
              </li>
            ))}
          </ol>
        )}
      </div>
    </section>
  );
}

